name: Run checks on push

on: push

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint

  svelte_check:
    name: Run Svelte check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Run svelte-check
        run: yarn svelte-check
