name: Build and create a release on tag push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build

      - id: package-metadata
        name: Extract project name and version
        run: |
          echo "name=$(jq -r .id manifest.json)" >> "$GITHUB_OUTPUT"
          echo "version=$(jq -r .version manifest.json)" >> "$GITHUB_OUTPUT"

      - id: upload-artifact
        name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.package-metadata.outputs.name }}-v${{ steps.package-metadata.outputs.version }}"
          if-no-files-found: error
          path: dist/zip/*

      - name: Create attestations
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: "${{ steps.package-metadata.outputs.name }}-v${{ steps.package-metadata.outputs.version }}"
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}

      - name: Draft a new release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: |
            dist/*.zip
            dist/main.js
            dist/manifest.json
