name: Build and upload artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build

      - id: package-metadata
        name: Extract project name and version
        run: |
          echo "name=$(jq -r .id manifest.json)" >> "$GITHUB_OUTPUT"
          echo "version=$(jq -r .version manifest.json)" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "${{ steps.package-metadata.outputs.name }}-v${{ steps.package-metadata.outputs.version }}"
          path: dist/zip/*
